- name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v1.1.2
        with:
          github_user_name: ${{ github.repository_owner }}
          svg_out_path: dist/github-contribution-grid-snake.svg